   USE[DFNB3]
GO

DROP TABLE stg.[NAICS_CODES_2017]

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON 
GO

CREATE TABLE  stg.[NAICS_CODES_2017](
    [Seq_No] [float] NULL,
    [2017_NAICS_US_Code] [float] NULL,
    [2017_NAICS_US_Title] [nvarchar](500) NULL
)ON [PRIMARY]
GO